name: Atlantiko
favicon: null
layout_spectrum: 0.86394
typography_spectrum: 0.51778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#e01c82'
    - '#569fe4'
    - '#09fd7b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
