analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#E01C82'
    - '#569FE4'
    - '#09FD7B'
  brandStrength: 1
  lightness: 0.5
  rhythmicContrast: 0.75
  saturation: 0.75
cta: {}
layout_spectrum: 1
name: Atlantiko
opengraph: {}
purpose: []
typography_spectrum: 0.51778
